FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Requisitos del backend
COPY backend/requirements.txt /app/requirements.txt 
RUN run: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copiamos el backend (igual lo montamos como volumen para dev)
COPY backend /app

EXPOSE 8000
