services:
  web:
    build: .
    container_name: smartquote_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: smartquote_db
    restart: always
    environment:
      POSTGRES_DB: smartquote
      POSTGRES_USER: erna
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5543:5432"

volumes:
  postgres_data:
