# Generated by Django 5.2.7 on 2025-10-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
    ]
