# Generated by Django 5.2.7 on 2025-10-12 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('category', models.CharField(choices=[('material', 'Material'), ('service', 'Servicio'), ('labor', 'Mano de obra'), ('other', 'Otro')], default='other', max_length=20)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='quotations.quotation')),
            ],
        ),
    ]
