# Generated by Django 5.2.7 on 2025-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotationexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
