# Generated by Django 5.2.7 on 2025-10-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_quotation_subtotal_alter_quotation_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
