# Generated by Django 5.2.7 on 2025-10-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotation_tax_alter_quotation_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
