# Generated by Django 5.2.7 on 2025-10-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_cancelled_at_quotation_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
