# Generated by Django 5.2.7 on 2025-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalprice',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='measure_units',
            field=models.CharField(default='', max_length=20),
        ),
    ]
