# Generated by Django 5.2.7 on 2025-10-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partially_paid', 'Parcialmente pagada'), ('paid', 'Pagada'), ('delivered', 'Entregada'), ('closed', 'Cerrada')], default='pending', max_length=20),
        ),
    ]
