# Generated by Django 5.2.7 on 2025-10-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('sales', '0003_alter_payment_amount_alter_sale_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sale', verbose_name='Venta asociada'),
        ),
    ]
