# Generated by Django 5.2.7 on 2025-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
