# Generated by Django 5.2.7 on 2025-10-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dynamic_price_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fuente de precio externo'),
        ),
    ]
