# Generated by Django 5.2.7 on 2025-10-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_dynamic_price_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metal_symbol',
            field=models.CharField(blank=True, help_text='Ejemplo: ALU, XCO, XCU, IRON', max_length=20, null=True, verbose_name='Símbolo del metal (opcional)'),
        ),
    ]
